# Generated by Django 4.2.9 on 2024-01-12 15:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad_religiosa', models.CharField(default='', max_length=255, verbose_name='Nombre de la Entidad Religiosa')),
                ('nombre_persona', models.CharField(default='', max_length=255, verbose_name='Nombre de la persona que responde la encuesta')),
                ('tipo_afiliacion', models.CharField(default='', max_length=255, verbose_name='Tipo de afiliación de la persona que responde la encuesta con la entidad religiosa')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cédula de la persona que responde')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('celular_extra', models.CharField(blank=True, null=True, verbose_name='Si tiene otro número de celular o número fijo de contacto escríbalo aquí')),
                ('zona_entidad_religiosa', models.CharField(choices=[('CABECERA', 'Cabecera (Zona urbana)'), ('CENTRO POBALDO', 'Centro poblado, rural disperso (Zona rural)'), ('OTRA', 'Otra')], default='', max_length=255, verbose_name='¿En que zona se encuentra ubicada la entidad religiosa que representa?')),
                ('otra_zona_entidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tipo de zona seleccionada')),
                ('anos_activa_entidad', models.PositiveIntegerField(verbose_name='¿Cuántos años lleva activa la entidad religiosa a la que representa?')),
                ('poblacion_entidad', multiselectfield.db.fields.MultiSelectField(choices=[('INDIGENA', 'Indígena'), ('AFROCOLOMBIANA', 'Afrocolombiano (a)'), ('CAMPESINA', 'Campesino (a)'), ('ROM', 'Rom (Gitanos)'), ('RAIZAL', 'Raizal'), ('OTRO', 'Otro (a)'), ('NINGUNO', 'Ninguno (a)')], default='', max_length=255, verbose_name='De acuerdo con su cultura, pueblo o rasgos físicos, ¿Qué población atienden y ayuda su entidad religiosa? (puede marcar varias)')),
                ('otra_poblacion_entidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tipo de población seleccionado')),
                ('grupos_personas', multiselectfield.db.fields.MultiSelectField(choices=[('Desplazado(a)', 'Desplazado(a)'), ('Reincorporado(a)', 'Reincorporado(a)'), ('Exiliado(a)', 'Exiliado(a)'), ('Migrante(a)', 'Migrante(a)'), ('Retornado(a)', 'Retornado(a)'), ('Refugiado(a)', 'Refugiado(a)'), ('Asilado(a)', 'Asilado(a)'), ('Otro(a)', 'Otro(a)'), ('Ninguno(a)', 'Ninguno(a)')], default='', max_length=255, verbose_name='Dentro del siguiente grupo de personas, ¿Cuál atiende y beneficia su entidad religiosa? (puede marcar varias)')),
                ('otros_grupos_personas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro grupo de personas seleccionado')),
                ('atiende_poblacion_discapacitada', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=255, verbose_name='¿Atiende población en la entidad religiosa en condición de discapacidad?')),
                ('tipos_discapacidades', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Física o motora', 'Física o motora'), ('Sensorial (Sentidos)', 'Sensorial (Sentidos)'), ('Intelectual', 'Intelectual'), ('Psíquica', 'Psíquica'), ('Visual', 'Visual'), ('Múltiple', 'Múltiple'), ('Otra', 'Otra'), ('Ninguna', 'Ninguna')], default='', max_length=255, null=True, verbose_name='Si respondió si en la pregunta anterior ¿Qué tipo de discapacidad tiene la población que atiende su entidad religiosa?')),
                ('otra_discapacidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro discapacidad seleccionada')),
                ('grupo_demografico', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0 a 5 años', '0 a 5 años'), ('6 a 11 años', '6 a 11 años'), ('12 a 17 años', '12 a 17 años'), ('18 a 23 años', '18 a 23 años'), ('24 a 29 años', '24 a 29 años'), ('30 a 35 años', '30 a 35 años'), ('36 a 40 años', '36 a 40 años'), ('41 a 46 años', '41 a 46 años'), ('47 a 52 años', '47 a 52 años'), ('53 a 59 años', '53 a 59 años'), ('60 a 65 años', '60 a 65 años'), ('66 a 71 años', '66 a 71 años'), ('72 a 77 años', '72 a 77 años'), ('77 a 82 años', '77 a 82 años'), ('83 a 88 años', '83 a 88 años'), ('89 a 94 años', '89 a 94 años'), ('95 y más', '95 y más')], default='', max_length=255, null=True, verbose_name='De acuerdo a la edad, ¿Cuál es el grupo demográfico principal al que sirve su Entidad religiosa? (puede seleccionar varios)')),
                ('distribucion_hombres_entidad', models.PositiveIntegerField(verbose_name='De acuerdo al sexo (Hombre),¿Cuál es la distribución porcentual de este en su Entidad religiosa? (ejemplo: 40% hombres)')),
                ('distribucion_mujeres_entidad', models.PositiveIntegerField(verbose_name='De acuerdo al sexo (Mujeres),¿Cuál es la distribución porcentual de este en su Entidad religiosa? (ejemplo: 60% mujeres)')),
            ],
        ),
    ]
