# Generated by Django 4.2.9 on 2024-01-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='distribucion_hombres_entidad',
            field=models.PositiveIntegerField(default=0, verbose_name='De acuerdo al sexo (Hombre),¿Cuál es la distribución porcentual de este en su Entidad religiosa? (ejemplo: 40% hombres)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='distribucion_mujeres_entidad',
            field=models.PositiveIntegerField(default=0, verbose_name='De acuerdo al sexo (Mujeres),¿Cuál es la distribución porcentual de este en su Entidad religiosa? (ejemplo: 60% mujeres)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='grupo_demografico',
            field=models.CharField(blank=True, choices=[('0 a 5 años', '0 a 5 años'), ('6 a 11 años', '6 a 11 años'), ('12 a 17 años', '12 a 17 años'), ('18 a 23 años', '18 a 23 años'), ('24 a 29 años', '24 a 29 años'), ('30 a 35 años', '30 a 35 años'), ('36 a 40 años', '36 a 40 años'), ('41 a 46 años', '41 a 46 años'), ('47 a 52 años', '47 a 52 años'), ('53 a 59 años', '53 a 59 años'), ('60 a 65 años', '60 a 65 años'), ('66 a 71 años', '66 a 71 años'), ('72 a 77 años', '72 a 77 años'), ('77 a 82 años', '77 a 82 años'), ('83 a 88 años', '83 a 88 años'), ('89 a 94 años', '89 a 94 años'), ('95 y más', '95 y más')], default='', max_length=255, null=True, verbose_name='De acuerdo a la edad, ¿Cuál es el grupo demográfico principal al que sirve su Entidad religiosa? (puede seleccionar varios)'),
        ),
    ]
