# Generated by Django 4.2.9 on 2024-01-12 21:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0002_alter_encuesta_distribucion_hombres_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='alcance_actividades_humanitarias',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Cuál es el alcance geográfico de las actividades humanitarias de su organización en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='alcance_actividades_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuál es el alcance geográfico de las actividades sociales de su Entidad en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='apoyo_economico_emergencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa brinda apoyo económico o asistencia financiera a sus líderes religiosos en caso de enfermedad o emergencia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='areas_temas_prioridad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name=' ¿Qué áreas o temas sociales son prioritarios para su Entidad (por ejemplo, educación, salud, alimentación, vivienda)?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='autoriza_uso_informacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Usted esta de acuerdo y autoriza el uso de la información conforme a las políticas de datos de PNUD? (puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='beneficios_implementado_seguridad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de beneficios o apoyo adicional le gustaría ver implementado o mejorado en su Entidad religiosa en relación con la seguridad social?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cambio_demografia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ha notado algún cambio en la demografía o en las creencias religiosas de la población a lo largo del tiempo? Si es así, ¿cómo ha afectado esto a su Entidad religiosa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='caracter_confesinal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Cuál es carácter confesional específico de su Entidad religiosa ?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='clase_social',
            field=models.CharField(blank=True, choices=[('Clase alta', 'Clase alta'), ('Clase media', 'Clase media'), ('Vulnerable', 'Vulnerable'), ('Pobre', 'Pobre')], default='', max_length=255, null=True, verbose_name='De acuerdo a la clase social, ¿Cuál la principal clase que atiende su Entidad religiosa? (seleccione SOLO una)(puede seleccionar solo una)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_agencias_humanitarios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Colabora su organización religiosa con agencias gubernamentales u organizaciones no religiosas en proyectos humanitarios en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_comunitarios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ha colaborado su Entidad religiosa con otras organizaciones no religiosas en proyectos comunitarios?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Colabora su Entidad religiosa con otras organizaciones religiosas o no religiosas en proyectos o iniciativas sociales en Colombia?.(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='como_finacia_proyectos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo financia su Entidad religiosa sus proyectos sociales (donaciones, fondos propios, colaboraciones)?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='como_interactua_comunidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo interactúa su Entidad religiosa con la comunidad local en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cuales_actividades_ods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuáles actividades o proyectos específicos ha llevado a cabo su organización para contribuir a la consecución de los ODS en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cuantas_personas_beneficiado',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='En el último año, ¿cuántas personas se han beneficiado de las actividades o proyectos de su Entidad religiosa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='enfoque_principal_servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuál es el enfoque principal de su Entidad religiosa en sus actividades y servicios?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='entidad_registrada',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name=' ¿La Entidad religiosa está registrada en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='es_lider_religioso',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Es usted un líder religioso en su Entidad religiosa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='experimentado_problema_seguridad_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ha experimentado algún problema o desafío específico relacionado con la seguridad social o los beneficios en su papel como líder religioso??'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='garantia_libertad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Cómo percibe la garantía de libertad de culto en su entidad local?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idioma_principal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Español', 'Español'), ('Inglés', 'Inglés'), ('Bilingüe o multilingüe', 'Bilingüe o multilingüe'), ('No estoy seguro/No aplicable.', 'No estoy seguro/No aplicable.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuál es el idioma/dialecto principal de su comunidad religiosa?(puede seleccionar solo una)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='impacto_comunidad_valores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ha tenido su Entidad religiosa un impacto significativo en la comunidad o la sociedad colombiana en términos de valores, ética y cultura?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='impacto_sociedad_valores',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ha tenido su Entidad religiosa un impacto significativo en la comunidad o la sociedad colombiana en términos de valores, ética y cultura?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='interactua_comunidad_humanitario',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿¿Cómo interactúa su organización religiosa con la comunidad local en Colombia en relación con el actuar humanitario?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='interactua_comunidad_local',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo interactúa su Entidad religiosa con la comunidad local en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='lideres_participan_instancia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Sus líderes y autoridades religiosas participan en alguna instancia de participación local o nacional? Si es así, por favor, especifique el tipo de instancia y su nivel de participación.'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_poblaciones',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios religiosos o de apoyo a grupos específicos poblaciones dentro de la sociedad colombiana?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios humanitarios a grupos específicos dentro de la sociedad colombiana?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_actividad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro actividad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_areas_temas_prioridad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra áreas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_beneficios_implementado_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros resultados'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_caracter_confesional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro actividad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_como_finacia_proyectos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra fuentes'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_cuales_actividades_ods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='Otras actividades relacionadas con los ODS (por favor, especifique)(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_enfoque_principal_servicios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros resultados'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_idioma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro idioma'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_participacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro actividad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_principales_inciativas_sociales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra iniciativas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_resultados_destacados',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros resultados'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_servicios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro actividad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otra_vocacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra vocación'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otros_departamentos_actividades',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Qué otros departamentos tiene actividades?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otros_municipios_actividades',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Qué otros municipios tiene actividades?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_caridad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa participa en actividades de caridad o servicio social en Colombia? Si es así, describa estas actividades.'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_humanitarias',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La organización religiosa participa activamente en actividades humanitarias en su territorio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_proyectos_sociales',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa participa activamente en proyectos o programas sociales en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participacion_poblacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo se promueve la participación de la población en las actividades de su Entidad religiosa?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='planes_futuras_humanitarias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuáles son sus planes o perspectivas futuras para continuar su labor humanitaria en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='principales_desafios_humanitarios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuáles son los principales desafíos que enfrenta su organización religiosa en Colombia en la actualidad en relación con su actuación humanitaria?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='principales_inciativas_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name=' ¿Cuáles son las principales iniciativas o proyectos sociales que la Entidad religiosa ha llevado a cabo en Colombia en los últimos años?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='promueve_participacion_humanitarias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades humanitarias?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='promueve_participacion_poblacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades sociales?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='proporciona_formacion_social',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Se proporciona algún tipo de formación o capacitación sobre seguridad social y beneficios para líderes religiosos en su Entidad religiosa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='proporciona_plan_pensiones',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa ofrece algún plan de jubilación o pensiones para sus líderes religiosos?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='proporciona_seguro_lideres',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Su Entidad religiosa proporciona algún tipo de seguro médico o de salud para sus líderes religiosos?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='proporciona_seguro_vida',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Su Entidad religiosa ofrece algún tipo de seguro de vida o seguro de incapacidad para sus líderes religiosos?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='realiza_cuidados_comunidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Habitualmente realiza alguna de las siguientes actividades de cuidado dirigidos a otros hogares o a su comunidad?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='relacionamiento_gobierno_entidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Cómo es el relacionamiento del gobierno local con la entidad religiosa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='resultados_destacados',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuáles son los resultados o impactos más destacados de las iniciativas sociales de su Entidad en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_alianzas_ongs',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Tiene la Entidad religiosa alianzas con otras instituciones u ONGs para abordar temas sociales en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa tiene organizaciones del sector, como fundaciones o colegios religiosos, registradas en Colombia?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_actividad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de actividad o programas realiza su Entidad religiosa para interactuar con la comunidad en general?(puede seleccionar solo una)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de servicios sociales ofrecen a la población local?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_vocacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de vocación tiene la Entidad religiosa en Colombia?'),
        ),
    ]
