# Generated by Django 4.2.9 on 2024-01-12 21:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0003_encuesta_alcance_actividades_humanitarias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='promueve_participacion_poblacion',
            new_name='promueve_participacion_poblacion_sociales',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='(puede seleccionar varios)',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Servicios religiosos abiertos al público.', 'Servicios religiosos abiertos al público.'), ('Eventos culturales o artísticos.', 'Eventos culturales o artísticos.'), ('Programas de voluntariado y servicio comunitario.', 'Programas de voluntariado y servicio comunitario.'), ('Programas educativos o talleres.', 'Programas educativos o talleres.'), ('Actividades deportivas o recreativas.', 'Actividades deportivas o recreativas.'), ('Programas de asistencia social.', 'Programas de asistencia social.'), ('No realiza actividades de interacción con la comunidad en general.', 'No realiza actividades de interacción con la comunidad en general.'), ('Otro', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_humanitarios',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios humanitarios a grupos específicos dentro de la sociedad colombiana?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios religiosos o de apoyo a grupos específicos dentro de la sociedad colombiana?'),
        ),
    ]
