# Generated by Django 4.2.9 on 2024-01-15 21:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0004_rename_promueve_participacion_poblacion_encuesta_promueve_participacion_poblacion_sociales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='(puede seleccionar varios)',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INVITACIONES_COMUNIDAD', 'A través de invitaciones y comunicaciones regulares a los miembros de la comunidad.'), ('EVENTOS_ATRACTIVOS', 'Organizando eventos y actividades atractivas para la participación.'), ('TOMA_DECISIONES_PARTICIPATIVA', 'Fomentando la toma de decisiones participativa en la planificación de actividades.'), ('VOLUNTARIADO_COMUNITARIO_OPCIONES', 'Ofreciendo oportunidades de voluntariado y servicio comunitario.'), ('FORMACION_GRUPOS_COMITES', 'Facilitando la formación de grupos y comités de interés.'), ('APOYO_RECURSOS_TALENTOS', 'Brindando apoyo y recursos para el desarrollo de talentos y habilidades de la comunidad.'), ('PLATAFORMAS_EN_LINEA_COMUNICACION', 'Utilizando plataformas en línea o redes sociales para la comunicación y participación.'), ('NO_PROMOVEMOS', 'No promovemos activamente la participación de la población local en nuestras actividades.')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='alcance_actividades_humanitarias',
            field=models.CharField(blank=True, choices=[('NIVEL_NACIONAL', 'Nivel nacional: Nuestras actividades humanitarias abarcan todo el territorio de Colombia.'), ('REGIONAL', 'Regional: Nuestras actividades se centran en una región específica o algunas regiones de Colombia.'), ('LOCAL', 'Local: Nos enfocamos en comunidades o áreas específicas dentro de una región.'), ('INTERNACIONAL', 'Internacional: Nuestra organización también realiza actividades humanitarias fuera de Colombia.'), ('NO_APLICA_ALCANCE_GEOGRAFICO', 'No aplicable: No estamos involucrados en actividades humanitarias en Colombia.')], default='', max_length=255, null=True, verbose_name='¿Cuál es el alcance geográfico de las actividades humanitarias de su organización en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='alcance_actividades_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LOCAL', 'Local, centrado en una comunidad o barrio específico.'), ('MUNICIPAL', 'Municipal, abarcando varias comunidades o barrios en un municipio.'), ('DEPARTAMENTAL', 'Departamental, extendiéndose a lo largo de un departamento o región.'), ('NACIONAL', 'Nacional, cubriendo múltiples departamentos en todo el país.'), ('INTERNACIONAL', 'Internacional, llevando a cabo actividades sociales a nivel internacional.'), ('NO_ACTIVIDADES_SOCIALES', 'No realizamos actividades sociales en Colombia.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cuál es el alcance geográfico de las actividades sociales de su Entidad en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='apoyo_economico_emergencia',
            field=models.CharField(blank=True, choices=[('BRINDA_APOYO', 'Sí, brinda apoyo económico en casos de enfermedad o emergencia.'), ('NO_BRINDA_APOYO', 'No, no brinda apoyo económico en estos casos.'), ('NO_SEGURO_APOYO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa brinda apoyo económico o asistencia financiera a sus líderes religiosos en caso de enfermedad o emergencia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='areas_temas_prioridad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EDUCACION', 'Educación'), ('SALUD', 'Salud'), ('ALIMENTACION', 'Alimentación'), ('VIVIENDA', 'Vivienda'), ('POBREZA', 'Pobreza'), ('OTROS', 'Otros'), ('NO_PRIORITARIOS', 'No tenemos áreas o temas sociales prioritarios.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name=' ¿Qué áreas o temas sociales son prioritarios para su Entidad (por ejemplo, educación, salud, alimentación, vivienda)?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='beneficios_implementado_seguridad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MAS_COBERTURA_MEDICA', 'Más cobertura médica.'), ('MEJORES_PLANES_JUBILACION', 'Mejores planes de jubilación.'), ('MAYOR_APOYO_FINANCIERO', 'Mayor apoyo financiero en casos de emergencia.'), ('OTROS', 'Otros (por favor, especifique).'), ('NO_SUGERENCIAS_ADICIONALES', 'No tengo sugerencias adicionales.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de beneficios o apoyo adicional le gustaría ver implementado o mejorado en su Entidad religiosa en relación con la seguridad social?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cambio_demografia',
            field=models.CharField(blank=True, choices=[('CAMBIOS_NOTADOS', 'Sí, hemos notado cambios en la demografía y las creencias religiosas de la población a lo largo del tiempo. ¿Cuáles?'), ('SIN_CAMBIOS_SIGNIFICATIVOS', 'No, no hemos notado cambios significativos en la demografía o las creencias religiosas de la población.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ha notado algún cambio en la demografía o en las creencias religiosas de la población a lo largo del tiempo? Si es así, ¿cómo ha afectado esto a su Entidad religiosa?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='caracter_confesinal',
            field=models.CharField(blank=True, choices=[('JUDAISMO', 'Judaísmo'), ('ISLAM', 'Islam'), ('CRISTIANISMO', 'Cristianismo'), ('BUDISMO', 'Budismo'), ('HINDUISMO', 'Hinduismo'), ('OTRO', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cuál es carácter confesional específico de su Entidad religiosa ?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_agencias_humanitarios',
            field=models.CharField(blank=True, choices=[('SI_COLABORA_REGULARMENTE', 'Sí, colabora regularmente con agencias gubernamentales en proyectos humanitarios en Colombia'), ('SI_COLABORA_OCASIONALMENTE', 'Sí, colabora ocasionalmente con agencias gubernamentales en proyectos humanitarios en Colombia.'), ('SI_COLABORA_CON_ORGANIZACIONES_NO_RELIGIOSAS', 'Sí, colabora con organizaciones no religiosas en proyectos humanitarios en Colombia.'), ('NO_NO_COLABORA', 'No, nuestra organización religiosa no colabora con agencias gubernamentales ni organizaciones no religiosas en proyectos humanitarios en Colombia.'), ('NO_APLICA', 'No aplicable / No estamos involucrados en proyectos humanitarios en Colombia.')], default='', max_length=255, null=True, verbose_name='¿Colabora su organización religiosa con agencias gubernamentales u organizaciones no religiosas en proyectos humanitarios en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_proyectos_comunitarios',
            field=models.CharField(blank=True, choices=[('COLABORACION_VARIOS_PROYECTOS', 'Sí, hemos colaborado en varios proyectos comunitarios con organizaciones no religiosas.'), ('COLABORACION_ALGUNOS_PROYECTOS', 'Sí, hemos colaborado en algunos proyectos comunitarios con organizaciones no religiosas.'), ('NO_COLABORACION_ORGANIZACIONES_NO_RELIGIOSAS', 'No, no hemos colaborado con organizaciones no religiosas en proyectos comunitarios.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ha colaborado su Entidad religiosa con otras organizaciones no religiosas en proyectos comunitarios?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_proyectos_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('COLABORACION_RELIGIOSAS', 'Sí, colaboramos con otras organizaciones religiosas en proyectos o iniciativas.'), ('COLABORACION_NO_RELIGIOSAS', 'Sí, colaboramos con organizaciones no religiosas en proyectos o iniciativas.'), ('NO_COLABORACION', 'No, no colaboramos con otras organizaciones religiosas o no religiosas en proyectos o iniciativas.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Colabora su Entidad religiosa con otras organizaciones religiosas o no religiosas en proyectos o iniciativas sociales en Colombia?.(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='como_finacia_proyectos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DONACIONES_MIEMBROS', 'Principalmente a través de donaciones de miembros y feligreses.'), ('FONDOS_PROPIOS', 'Usando fondos propios de la Entidad religiosa.'), ('COLABORACIONES_ORGANIZACIONES', 'Colaborando con otras organizaciones o entidades para obtener financiamiento.'), ('DONACIONES_EMPRESAS', 'Recibiendo donaciones de empresas u organizaciones externas.'), ('SUBVENCIONES_GOBIERNO', 'Apoyándose en subvenciones gubernamentales o de instituciones internacionales.'), ('OTRAS_FUENTES', 'Otras fuentes de financiamiento (por favor, especifique).'), ('NO_FINANCIAMOS', 'No financiamos proyectos sociales.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cómo financia su Entidad religiosa sus proyectos sociales (donaciones, fondos propios, colaboraciones)?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='como_interactua_comunidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SERVICIOS_RELIGIOSOS', 'A través de servicios religiosos y actividades abiertas al público.'), ('EVENTOS_CULTURALES', 'Organizando eventos y actividades culturales para la comunidad.'), ('VOLUNTARIADO_SERVICIO_COMUNITARIO', 'Fomentando programas de voluntariado y servicio comunitario.'), ('PROGRAMAS_EDUCATIVOS_TALLERES', 'Ofreciendo programas educativos o talleres para la comunidad.'), ('ACTIVIDADES_DEPORTIVAS_RECREATIVAS', 'Promoviendo actividades deportivas o recreativas para todos.'), ('ASISTENCIA_SOCIAL', 'Realizando programas de asistencia social para quienes lo necesitan.'), ('PLATAFORMAS_EN_LINEA_REDES_SOCIALES', 'Utilizando plataformas en línea o redes sociales para interactuar con la comunidad.'), ('NO_INTERACCION', 'No interactuamos activamente con la comunidad local.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cómo interactúa su Entidad religiosa con la comunidad local en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cuales_actividades_ods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PROYECTOS_EDUCACION', 'Proyectos de educación para promover la igualdad de género y el acceso a la educación de calidad.'), ('INICIATIVAS_SALUD', 'Iniciativas de salud para mejorar el bienestar y la atención médica de comunidades vulnerables.'), ('PROGRAMAS_ALIMENTACION_NUTRICION', 'Programas de alimentación y nutrición para combatir la malnutrición y el hambre.'), ('PROYECTOS_VIVIENDA', 'Proyectos de vivienda y desarrollo de infraestructura para reducir la desigualdad en el acceso a la vivienda adecuada.'), ('PROGRAMAS_EMPRENDIMIENTO', 'Programas de empoderamiento económico para combatir la pobreza y promover el empleo digno.'), ('INICIATIVAS_MEDIO_AMBIENTE', 'Iniciativas de protección del medio ambiente y sostenibilidad.'), ('PROYECTOS_PROMOCION_PAZ', 'Proyectos de promoción de la paz, la justicia y las instituciones sólidas.'), ('OTRAS_ACTIVIDADES_ODS', 'Otras actividades relacionadas con los ODS.'), ('NO_ACTIVIDADES_ESPECIFICAS_ODS', 'No hemos llevado a cabo actividades específicas relacionadas con los ODS en Colombia.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cuáles actividades o proyectos específicos ha llevado a cabo su organización para contribuir a la consecución de los ODS en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cuantas_personas_beneficiado',
            field=models.CharField(blank=True, choices=[('MENOS_100_PERSONAS', 'Menos de 100 personas.'), ('ENTRE_100_Y_500_PERSONAS', 'Entre 100 y 500 personas.'), ('ENTRE_500_Y_1000_PERSONAS', 'Entre 500 y 1,000 personas.'), ('MAS_1000_PERSONAS', 'Más de 1,000 personas.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='En el último año, ¿cuántas personas se han beneficiado de las actividades o proyectos de su Entidad religiosa?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='enfoque_principal_servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ENFOQUE_CONFESIONAL', 'Enfoque Confesional'), ('ENFOQUE_ASOCIATIVO', 'Enfoque Asociativo (Asociación, Federación, Confederación)'), ('ORGANIZACION_SECTOR_RELIGIOSO', 'Organización del Sector Religioso (OSR)'), ('BIIR', 'BIIR (Bienes de Interés de Interés Religioso)'), ('CONSEJO_CONSULTIVO_MUJERES', 'Consejo Consultivo de Mujeres'), ('CONSEJO_JUVENTUD', 'Consejo de Juventud'), ('GESTORES_PAZ_RECONCILIACION', 'Gestores de Paz y Reconciliación'), ('ENFOQUE_RURAL', 'Enfoque Rural'), ('DEPARTAMENTO_DISTRITO_MUNICIPAL', 'Departamento, Distrito y Municipal'), ('MEDIOS_COMUNICACION', 'Medios de Comunicación (Emisoras, Canales, Periódicos)'), ('EDUCACION', 'Educación'), ('PAZ', 'Paz'), ('OTRO', 'Otro (por favor, especifique)'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cuál es el enfoque principal de su Entidad religiosa en sus actividades y servicios?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='entidad_registrada',
            field=models.CharField(blank=True, choices=[('REGISTRADA_SI', 'Sí, la Entidad religiosa está registrada en Colombia.'), ('REGISTRADA_NO', 'No, la Entidad religiosa no está registrada en Colombia.'), ('REGISTRADA_TRANSITO', 'No, pero está en tránsito'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name=' ¿La Entidad religiosa está registrada en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='es_lider_religioso',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable')], default='', max_length=255, null=True, verbose_name='¿Es usted un líder religioso en su Entidad religiosa?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='experimentado_problema_seguridad_social',
            field=models.CharField(blank=True, choices=[('ENFRENTADO_DESAFIOS', 'Sí, he enfrentado desafíos relacionados con la seguridad social.'), ('SIN_DESAFIOS', 'No, no he enfrentado desafíos en este aspecto.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ha experimentado algún problema o desafío específico relacionado con la seguridad social o los beneficios en su papel como líder religioso?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='garantia_libertad',
            field=models.CharField(blank=True, choices=[('GARANTIA_PLENAMENTE', 'La entidad local garantiza plenamente la libertad de culto y religión.'), ('GARANTIA_CIERTAS', 'La entidad local ofrece ciertas garantías, pero podría mejorar en este aspecto.'), ('RESTRICCIONES_SIGNIFICATIVAS', 'La entidad local presenta restricciones significativas a la libertad de culto y religión.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cómo percibe la garantía de libertad de culto en su entidad local?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='impacto_comunidad_valores',
            field=models.CharField(blank=True, choices=[('IMPACTO_SI', 'Sí'), ('IMPACTO_NO', 'No'), ('NO_APLICA', 'No aplica')], default='', max_length=255, null=True, verbose_name='¿Ha tenido su Entidad religiosa un impacto significativo en la comunidad o la sociedad colombiana en términos de valores, ética y cultura?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='impacto_sociedad_valores',
            field=models.CharField(blank=True, choices=[('IMPACTO_SIGNIFICATIVO', 'Sí, hemos tenido un impacto significativo en la promoción de valores, ética y cultura.'), ('IMPACTO_MODERADO', 'Sí, hemos tenido un impacto moderado en estos aspectos.'), ('NO_IMPACTO_SIGNIFICATIVO', 'No hemos tenido un impacto significativo en estos aspectos.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ha tenido su Entidad religiosa un impacto significativo en la comunidad o la sociedad colombiana en términos de valores, ética y cultura?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='interactua_comunidad_humanitario',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PROGRAMAS_PARTICIPACION_COMUNITARIA', 'Establecemos programas de participación comunitaria y colaboramos activamente con líderes locales.'), ('EVENTOS_TALLERES_ABIERTOS', 'Organizamos eventos y talleres abiertos a la comunidad para fomentar la participación y la colaboración.'), ('COORDINACION_ORGANIZACIONES_COMUNITARIAS', 'Trabajamos en estrecha coordinación con organizaciones comunitarias existentes en Colombia.'), ('PROMOCION_VOLUNTARIADO_LOCAL', 'Promovemos la participación de voluntarios locales en nuestros proyectos humanitarios.'), ('CONCIENCIACION_EDUCACION_COMUNITARIA', 'Realizamos campañas de concienciación y educación en la comunidad sobre temas humanitarios.'), ('TODAS_LAS_ANTERIORES', 'Todas las anteriores.'), ('NO_INTERACTUA_DIRECTAMENTE', 'No interactuamos de manera directa con la comunidad local en Colombia en relación con el actuar humanitario.')], default='', max_length=255, null=True, verbose_name='¿¿Cómo interactúa su organización religiosa con la comunidad local en Colombia en relación con el actuar humanitario?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='interactua_comunidad_local',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SERVICIOS_RELIGIOSOS', 'A través de servicios religiosos y actividades abiertas al público.'), ('EVENTOS_CULTURALES', 'Organizando eventos culturales o artísticos para la comunidad.'), ('VOLUNTARIADO_COMUNITARIO', 'Fomentando programas de voluntariado y servicio comunitario.'), ('PROGRAMAS_EDUCATIVOS', 'Ofreciendo programas educativos o talleres para la comunidad.'), ('ACTIVIDADES_DEPORTIVAS', 'Promoviendo actividades deportivas o recreativas para todos.'), ('ASISTENCIA_SOCIAL', 'Realizando programas de asistencia social para quienes lo necesitan.'), ('PLATAFORMAS_EN_LINEA', 'Utilizando plataformas en línea o redes sociales para interactuar con la comunidad.'), ('NO_INTERACCION', 'No interactuamos activamente con la comunidad local.')], default='', max_length=255, null=True, verbose_name='¿Cómo interactúa su Entidad religiosa con la comunidad local en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='lideres_participan_instancia',
            field=models.CharField(blank=True, choices=[('PARTICIPACION_LOCAL', 'Sí, nuestros líderes participan activamente en instancias locales de participación, como consejos de vecinos o juntas de acción comunal.'), ('PARTICIPACION_LOCAL_NACIONAL', 'Sí, nuestros líderes participan en instancias locales y nacionales de participación, como comités ciudadanos o asambleas.'), ('PARTICIPACION_NACIONAL', 'Sí, nuestros líderes participan en instancias nacionales de participación, como organizaciones religiosas a nivel nacional o coaliciones interreligiosas.'), ('NO_PARTICIPACION', 'No, nuestros líderes no participan en instancias de participación local o nacional.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Sus líderes y autoridades religiosas participan en alguna instancia de participación local o nacional? Si es así, por favor, especifique el tipo de instancia y su nivel de participación.'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_humanitarios',
            field=models.CharField(blank=True, choices=[('grupo_vulnerables', 'Sí, nos enfocamos en brindar servicios humanitarios a grupos vulnerables como niños, ancianos o personas con discapacidades.'), ('comunidades_indigenas', 'Sí, nuestras actividades humanitarias están dirigidas principalmente a comunidades indígenas o afrocolombianas.'), ('desastres_naturales', 'Sí, nos centramos en brindar servicios a personas afectadas por desastres naturales en Colombia.'), ('desplazados_conflictos', 'Sí, colaboramos con organizaciones que trabajan específicamente con grupos desplazados por conflictos en Colombia.'), ('general_sociedad_colombiana', 'No, ofrecemos servicios humanitarios de manera general a la sociedad colombiana sin focalizarnos en grupos específicos.')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios humanitarios a grupos específicos dentro de la sociedad colombiana?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_poblaciones',
            field=models.CharField(blank=True, choices=[('SERVICIOS_SI', 'Sí, ofrecemos servicios religiosos o de apoyo a grupos específicos (abrir a cuáles).'), ('SERVICIOS_NO', 'No, no ofrecemos servicios religiosos o de apoyo a grupos específicos.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios religiosos o de apoyo a grupos específicos poblaciones dentro de la sociedad colombiana?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad',
            field=models.CharField(blank=True, choices=[('SERVICIOS_ESPECIFICOS', 'Sí, ofrecemos servicios religiosos o de apoyo a grupos específicos, como niños, jóvenes o personas mayores. ¿Cuáles?'), ('ABIERTO_TODA_COMUNIDAD', 'No, nuestros servicios religiosos son abiertos a toda la comunidad sin distinción de grupos específicos.'), ('NO_OFRECE_SERVICIOS', 'No ofrecemos servicios religiosos en Colombia.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Ofrece servicios religiosos o de apoyo a grupos específicos dentro de la sociedad colombiana?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_cuales_actividades_ods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PEDAGOGIA_PARA_LA_PAZ', 'Pedagogía para la paz, reconciliación.'), ('TALLERES_SENSIBILIZACION', 'Talleres de sensibilización para el perdón, paz y reconciliación.'), ('INCIDENCIA_PROMOCION_PAZ', 'Incidencia o participación en promoción en temas de paz.'), ('ACTIVIDADES_ARTISTICAS_LUDICAS_DEPORTIVAS', 'Actividades artísticas, lúdicas o deportivas que aporten a la construcción de la paz.'), ('EDUCACION_PARA_EL_TRABAJO', 'Educación para el trabajo (capacitación laboral).'), ('EDUCACION_DERECHOS_HUMANOS', 'Educación en Derechos Humanos.'), ('PROYECTOS_PRODUCTIVOS', 'Proyectos productivos.'), ('PREVENCION_EMBARAZO_ADOLESCENTE', 'Programas de prevención de embarazo adolescente.'), ('PROMOCION_EQUIDAD_GENERO', 'Promoción de equidad de género.'), ('DERECHOS_SEXUALES_REPRODUCTIVOS', 'Derechos sexuales y reproductivos.'), ('SUPERACION_POBREZA', 'Superación de la pobreza.'), ('PROYECTOS_AMBIENTALES', 'Proyectos ambientales.'), ('LIDERAZGO_JUVENIL', 'Acción y liderazgo juvenil.'), ('LIDERAZGO_MUJERES', 'Acción y liderazgo de mujeres.'), ('PROYECTOS_INICIATIVA_JOVENES', 'Proyectos de iniciativa de jóvenes.'), ('PROYECTOS_INICIATIVA_MUJERES', 'Proyectos de iniciativa de mujeres.'), ('PREVENCION_ATENCION_VIOLENCIA_INTRA', 'Prevención y/o atención a la violencia intrafamiliar.'), ('PREVENCION_ATENCION_VIOLENCIA_CONTRA_MUJER', 'Prevención y/o atención a la violencia contra la mujer.'), ('PREVENCION_ATENCION_VIOLENCIA_SEXUAL', 'Prevención y/o atención a la violencia sexual.'), ('PREVENCION_ATENCION_VIOLENCIA_ESCOLAR', 'Prevención y/o atención a la violencia escolar.'), ('PREVENCION_TRABAJO_PANDILLAS_MICRO_TRAFICO', 'Prevención o trabajo en temas de pandillas y micro tráfico.'), ('TRABAJO_PROTECCION_GARANTIA_DERECHOS_DIVERSIDAD_ETNICA_CULTURAL', 'Trabajo en protección/garantía de derechos de la diversidad étnica y cultural.'), ('OBJECION_CONCIENCIA', 'Objeción de conciencia.'), ('PREVENCION_TRABAJO_VIOLENCIA_COTIDIANA_RIÑAS_CALLEJERAS', 'Prevención o trabajo en temas de violencia cotidiana/riñas callejeras.')], default='', max_length=255, null=True, verbose_name='Otras actividades relacionadas con los ODS (por favor, especifique)(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_caridad',
            field=models.CharField(blank=True, choices=[('PARTICIPACION_SI', 'Sí, participamos en actividades de caridad y servicio social.'), ('PARTICIPACION_NO', 'No, no participamos en actividades de caridad o servicio social.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa participa en actividades de caridad o servicio social en Colombia? Si es así, describa estas actividades.'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_humanitarias',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NO_SABE_NO_APLICA', 'No sabe/No aplica')], default='', max_length=255, null=True, verbose_name='¿La organización religiosa participa activamente en actividades humanitarias en su territorio?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_proyectos_sociales',
            field=models.CharField(blank=True, choices=[('PARTICIPACION_ACTIVAMENTE', 'Sí, participamos activamente en proyectos y programas sociales en Colombia.'), ('NO_PARTICIPACION_SOCIAL', 'No, no participamos en proyectos ni programas sociales en Colombia.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa participa activamente en proyectos o programas sociales en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participacion_poblacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INVITACIONES_Y_COMUNICACIONES', 'A través de invitaciones y comunicaciones regulares a los miembros.'), ('EVENTOS_Y_ACTIVIDADES', 'Mediante la organización de eventos y actividades atractivas.'), ('PARTICIPACION_EN_DECISIONES', 'Fomentando la participación activa en la toma de decisiones.'), ('VOLUNTARIADO_Y_SERVICIO_COMUNITARIO', 'Ofreciendo oportunidades de voluntariado y servicio comunitario.'), ('GRUPOS_Y_COMITES', 'Facilitando la formación de grupos y comités de interés.'), ('APOYO_AL_DESARROLLO_DE_TALENTOS', 'Brindando apoyo y recursos para el desarrollo de talentos y habilidades.'), ('PLATAFORMAS_EN_LINEA_REDES_SOCIALES', 'Utilizando plataformas en línea o redes sociales para la comunicación.'), ('NO_PROMUEVE_PARTICIPACION', 'No se promueve activamente la participación de la población.'), ('OTRO', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Cómo se promueve la participación de la población en las actividades de su Entidad religiosa?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='planes_futuras_humanitarias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AMPLIAR_OPERACIONES', 'Ampliar nuestras operaciones humanitarias en nuevas áreas geográficas en Colombia.'), ('DIVERSIFICAR_MEJORAR_PROGRAMAS', 'Diversificar y mejorar nuestros programas y servicios humanitarios.'), ('FORTALECER_COLABORACION', 'Fortalecer la colaboración con otras organizaciones humanitarias en Colombia.'), ('INCREMENTAR_RECAUDACION_FONDOS', 'Incrementar nuestros esfuerzos de recaudación de fondos para financiar proyectos a largo plazo.'), ('MEJORAR_PARTICIPACION_EMPODERAMIENTO', 'Mejorar la participación y el empoderamiento de la comunidad local en la toma de decisiones.'), ('INVERTIR_FORMACION_CAPACITACION', 'Invertir en la formación y capacitación continua de nuestro personal y voluntarios.'), ('ADAPTARNOS_CAMBIANTES_NECESIDADES', 'Adaptarnos a las cambiantes necesidades de la población colombiana a la que servimos.'), ('EVALUAR_MEDIR_IMPACTO', 'Evaluar y medir regularmente el impacto de nuestros proyectos humanitarios.'), ('BUSCAR_OPORTUNIDADES_PROMOVER_PAZ', 'Buscar oportunidades para promover la paz y la reconciliación en áreas afectadas por conflictos.'), ('TODAS_LAS_ANTERIORES', 'Todas las anteriores.'), ('NO_TENEMOS_PLANES', 'No tenemos planes futuros específicos en este momento.')], default='', max_length=255, null=True, verbose_name='¿Cuáles son sus planes o perspectivas futuras para continuar su labor humanitaria en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='poblacion_entidad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INDIGENA', 'Indígena'), ('AFROCOLOMBIANA', 'Afrocolombiano (a)'), ('CAMPESINA', 'Campesino (a)'), ('ROM', 'Rom (Gitanos)'), ('RAIZAL', 'Raizal'), ('OTRO', 'Otro (a)'), ('NINGUNO', 'Ninguno (a)')], default='', max_length=255, verbose_name='De acuerdo con su cultura, pueblo o rasgos físicos, ¿Qué población atienden y ayuda su entidad religiosa?(puede marcar varias)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='principales_desafios_humanitarios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LIMITACIONES_FINANCIERAS', 'Limitaciones financieras y dificultades para recaudar fondos suficientes.'), ('ACCESO_LIMITADO_AREAS_REMOTAS', 'Acceso limitado a áreas remotas o afectadas por conflictos.'), ('CAMBIOS_LEGISLACION_POLITICAS', 'Cambios en la legislación o políticas gubernamentales que afectan nuestras actividades.'), ('FALTA_PERSONAL_VOLUNTARIOS_CAPACITADOS', 'Falta de personal y voluntarios capacitados.'), ('COMPETENCIA_CON_OTRAS_ORGANIZACIONES', 'Competencia con otras organizaciones por recursos y apoyo.'), ('OBSTACULOS_CULTURALES_RELIGIOSOS', 'Obstáculos culturales o religiosos en la relación con la comunidad local.'), ('DESCONFIANZA_POBLACION_LOCAL', 'Desconfianza de la población local hacia organizaciones religiosas.'), ('PROBLEMAS_SEGURIDAD_PERSONAL_VOLUNTARIOS', 'Problemas de seguridad para nuestro personal y voluntarios.'), ('CAMBIOS_NECE_SOCIEDAD_SERVICIO', 'Cambios en las necesidades de la población a la que servimos.'), ('OTROS_DESAFIOS', 'Otros desafíos no mencionados anteriormente.')], default='', max_length=255, null=True, verbose_name='¿Cuáles son los principales desafíos que enfrenta su organización religiosa en Colombia en la actualidad en relación con su actuación humanitaria?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='principales_inciativas_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PROYECTOS_EDUCATIVOS', 'Proyectos educativos.'), ('PROGRAMAS_SALUD', 'Programas de salud y atención médica.'), ('INICIATIVAS_ALIMENTACION', 'Iniciativas de alimentación para comunidades necesitadas.'), ('PROGRAMAS_VIVIENDA', 'Programas de vivienda para población vulnerable.'), ('APOYO_NINOS_JOVENES', 'Actividades de apoyo a niños y jóvenes en riesgo.'), ('PROYECTOS_COMUNITARIOS', 'Proyectos de desarrollo comunitario.'), ('OTROS_INICIATIVAS', 'Otros'), ('NO_LLEVADO_A_CABO', 'No hemos llevado a cabo iniciativas o proyectos sociales en Colombia en los últimos años.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name=' ¿Cuáles son las principales iniciativas o proyectos sociales que la Entidad religiosa ha llevado a cabo en Colombia en los últimos años?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='promueve_participacion_humanitarias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CAPACITACION_LIDERES_COMUNITARIOS', 'Fomentamos la capacitación y formación de líderes comunitarios locales para que participen en la planificación y ejecución de proyectos humanitarios.'), ('REUNIONES_ASAMBLEAS_ABIERTAS', 'Organizamos reuniones y asambleas abiertas a la comunidad para recoger sus opiniones y sugerencias sobre nuestras actividades humanitarias.'), ('GRUPOS_VOLUNTARIOS_LOCALES', 'Establecemos grupos de voluntarios locales que colaboran activamente en la implementación de proyectos.'), ('COLABORACION_ORGANIZACIONES_COMUNITARIAS', 'Colaboramos estrechamente con organizaciones comunitarias existentes en Colombia para trabajar de manera conjunta en proyectos humanitarios.'), ('PARTICIPACION_COMUNIDAD_TOMA_DECISIONES', 'Promovemos la participación de la comunidad en la toma de decisiones relacionadas con nuestros proyectos humanitarios a través de consultas y encuestas.'), ('TODAS_LAS_ANTERIORES_PARTICIPACION_COMUNITARIA', 'Todas las anteriores.'), ('NO_PROMOVEMOS_PARTICIPACION_COMUNITARIA', 'No promovemos la participación de la población local en nuestras actividades humanitarias.')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades humanitarias?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='promueve_participacion_poblacion_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INVITACIONES_COMUNICACIONES', 'A través de invitaciones y comunicaciones regulares a los miembros de la comunidad.'), ('EVENTOS_ACTIVIDADES_ATRACTIVAS', 'Organizando eventos y actividades atractivas para la participación.'), ('TOMA_DECISIONES_PARTICIPATIVA', 'Fomentando la toma de decisiones participativa en la planificación de actividades.'), ('OPORTUNIDADES_VOLUNTARIADO', 'Ofreciendo oportunidades de voluntariado y servicio comunitario.'), ('FORMACION_GRUPOS_COMITES', 'Facilitando la formación de grupos y comités de interés.'), ('APOYO_RECURSOS_DESARROLLO_TALENTOS', 'Brindando apoyo y recursos para el desarrollo de talentos y habilidades de la comunidad.'), ('PLATAFORMAS_EN_LINEA_REDES_SOCIALES', 'Utilizando plataformas en línea o redes sociales para la comunicación y participación.'), ('NO_PROMUEVE_PARTICIPACION', 'No promovemos activamente la participación de la población local en nuestras actividades sociales.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cómo promueve la participación de la población local en sus actividades sociales?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='proporciona_formacion_social',
            field=models.CharField(blank=True, choices=[('SE_PROPORCIONA', 'Sí, se proporciona formación y capacitación sobre seguridad social y beneficios.'), ('NO_SE_PROPORCIONA', 'No, no se proporciona formación ni capacitación en este tema.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Se proporciona algún tipo de formación o capacitación sobre seguridad social y beneficios para líderes religiosos en su Entidad religiosa?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='proporciona_plan_pensiones',
            field=models.CharField(blank=True, choices=[('OFRECE_PLAN', 'Sí, ofrece un plan de jubilación o pensiones.'), ('NO_OFRECE_PLAN', 'No, no ofrece ningún plan de jubilación o pensiones.'), ('NO_SEGURO_PLAN_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa ofrece algún plan de jubilación o pensiones para sus líderes religiosos?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='proporciona_seguro_lideres',
            field=models.CharField(blank=True, choices=[('SEGURO_COMPLETO', 'Sí, proporciona un seguro médico completo.'), ('SEGURO_BASICO', 'Sí, proporciona un seguro médico básico.'), ('NO_PROPORCIONA', 'No, no proporciona seguro médico.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Su Entidad religiosa proporciona algún tipo de seguro médico o de salud para sus líderes religiosos?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='proporciona_seguro_vida',
            field=models.CharField(blank=True, choices=[('OFRECE_SEGURO', 'Sí, ofrece seguro de vida y/o seguro de incapacidad.'), ('NO_OFRECE_SEGURO', 'No, no ofrece este tipo de seguro.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Su Entidad religiosa ofrece algún tipo de seguro de vida o seguro de incapacidad para sus líderes religiosos?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='realiza_cuidados_comunidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MANTENIMIENTO_VESTUARIO', 'Mantenimiento del vestuario (Lavar, planchar o guardar la ropa de las personas del hogar, Reparar ropa, cobijas, maletas o calzado de las personas del hogar, Llevar o recoger ropa o zapatos de la lavandería o zapatería)'), ('LIMPIEZA_MANTENIMIENTO_REPARACION', 'Limpieza, mantenimiento y reparación (Barrer, trapear, tender camas, sacudir el polvo, sacar la basura; Cuidar mascotas o animales de compañía, cuidar el jardín, limpiar el vehículo; Traer combustible para uso de la comunidad diferente a leña; Reparar o hacer instalaciones en otras viviendas diferente a la suya)'), ('CUIDADO_FISICO', 'Cuidado físico como apoyo a integrantes de la comunidad u otras comunidades (Alimentar a una persona o ayudarle a hacerlo; Bañar o vestir a una persona o ayudarle a hacerlo; Suministrar medicamentos, hacer terapias o dar tratamiento a enfermedades)'), ('CUIDADO_NINOS', 'Cuidado de niños, niñas y adolescentes integrantes de su comunidad u otras comunidades (Jugar; Leer o contar cuentos; Llevar al parque)'), ('APOYO_PERSONAS', 'Apoyo a personas de su comunidad u otras comunidades (Ayudar con tareas o trabajos escolares; Acompañar a citas médicas, odontológicas, urgencias, terapias u otras atenciones en salud. Llevar o traer a personas del hogar al sitio de estudio, trabajo o a eventos culturales deportivos o recreativos)'), ('CULTIVO_COSECHA', 'Cultivo y cosecha de productos agrícolas o de huerta/cuidado de animales para el consumo de su comunidad)'), ('OTRAS_ACTIVIDADES', 'Otras')], default='', max_length=255, null=True, verbose_name='¿Habitualmente realiza alguna de las siguientes actividades de cuidado dirigidos a otros hogares o a su comunidad?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='relacionamiento_gobierno_entidad',
            field=models.CharField(blank=True, choices=[('RELACION_POSITIVA', 'El gobierno local mantiene una relación positiva y colaborativa con la entidad religiosa.'), ('RELACION_NEUTRAL', 'El gobierno local tiene una relación neutral con la entidad religiosa, sin interacciones significativas.'), ('RELACION_TENSA', 'El gobierno local tiene una relación tensa o conflictiva con la entidad religiosa.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cómo es el relacionamiento del gobierno local con la entidad religiosa?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='resultados_destacados',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MEJORA_EDUCACION', 'Mejora en la educación de la comunidad.'), ('ACCESO_SERVICIOS_SALUD', 'Mayor acceso a servicios de salud.'), ('REDUCCION_MALNUTRICION', 'Reducción de la malnutrición.'), ('INCREMENTO_CALIDAD_VIDA', 'Incremento en la calidad de vida de comunidades vulnerables.'), ('APOYO_POBLACIONES_RIESGO', 'Apoyo a poblaciones en situación de riesgo.'), ('FORTALECIMIENTO_COHESION_COMUNITARIA', 'Fortalecimiento de la cohesión comunitaria.'), ('OTRAS_MEJORAS_SOCIALES', 'Otras mejoras sociales (por favor, especifique).'), ('NO_ACTIVIDADES_SOCIALES', 'No hemos realizado iniciativas sociales en Colombia.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Cuáles son los resultados o impactos más destacados de las iniciativas sociales de su Entidad en Colombia?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_alianzas_ongs',
            field=models.CharField(blank=True, choices=[('ALIANZAS_SI', 'Sí, tenemos alianzas con otras instituciones u ONGs para abordar temas sociales.'), ('ALIANZAS_NO', 'No, no tenemos alianzas con otras instituciones u ONGs para abordar temas sociales.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Tiene la Entidad religiosa alianzas con otras instituciones u ONGs para abordar temas sociales en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_organizaciones_sector',
            field=models.CharField(blank=True, choices=[('ORGANIZACIONES_REGISTRADAS_SI', 'Sí, tiene organizaciones del sector registradas.'), ('ORGANIZACIONES_REGISTRADAS_NO', 'No, no tiene organizaciones del sector registradas.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿La Entidad religiosa tiene organizaciones del sector, como fundaciones o colegios religiosos, registradas en Colombia?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Asistencia alimentaria (por ejemplo, bancos de alimentos).', 'Asistencia alimentaria (por ejemplo, bancos de alimentos).'), ('Refugio o vivienda temporal para personas sin hogar.', 'Refugio o vivienda temporal para personas sin hogar.'), ('Apoyo psicológico o de salud mental.', 'Apoyo psicológico o de salud mental.'), ('Programas de apoyo a familias en situación de vulnerabilidad.', 'Programas de apoyo a familias en situación de vulnerabilidad.'), ('Ayuda financiera o asesoramiento económico.', 'Ayuda financiera o asesoramiento económico.'), ('Servicios de atención médica o clínicas de salud.', 'Servicios de atención médica o clínicas de salud.'), ('Programas de educación para adultos.', 'Programas de educación para adultos.'), ('Programas de inclusión y apoyo a inmigrantes y refugiados.', 'Programas de inclusión y apoyo a inmigrantes y refugiados.'), ('Apoyo espiritual para el sector penitenciario y carcelario.', 'Apoyo espiritual para el sector penitenciario y carcelario.'), ('NO_OFRECEMOS_SERVICIOS', 'No ofrecemos servicios sociales.'), ('OTRO', 'Otro')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de servicios sociales ofrecen a la población local?(puede seleccionar varios)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_vocacion',
            field=models.CharField(blank=True, choices=[('IGLESIA', 'Iglesia'), ('CONFESIONAL', 'Confesional'), ('DENOMINACION', 'Denominación'), ('ASOCIACIONES_PASTORES', 'Asociaciones de pastores'), ('FEDERACION_O_CONFEDERACION', 'Federación o confederación'), ('OTRA', 'Otra (por favor especifique)'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name='¿Qué tipo de vocación tiene la Entidad religiosa en Colombia?'),
        ),
    ]
