# Generated by Django 4.2.9 on 2024-01-16 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0005_alter_encuesta__puede_seleccionar_varios__and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
