# Generated by Django 4.2.9 on 2024-01-16 03:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0007_alter_encuesta__puede_seleccionar_varios__and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='otra_idioma',
            new_name='otro_idioma',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='otra_beneficios_implementado_seguridad',
            new_name='otros_resultados_destacados',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='otra_caracter_confesional',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='otra_enfoque_principal_servicios',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='otra_resultados_destacados',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='otra_servicios',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otro_caracter_confesional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro caracter confesional'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otro_enfoque_principal_servicios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro enfoque principal'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otro_servicio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro servicio'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otros_beneficios_implementado_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros beneficio implementado en seguridad social'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='autoriza_uso_informacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=255, null=True, verbose_name='¿Usted esta de acuerdo y autoriza el uso de la información conforme a las políticas de datos de PNUD?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_actividad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra actividad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_participacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra participacion'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='poblacion_entidad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INDIGENA', 'Indígena'), ('AFROCOLOMBIANA', 'Afrocolombiano (a)'), ('CAMPESINA', 'Campesino (a)'), ('ROM', 'Rom (Gitanos)'), ('RAIZAL', 'Raizal'), ('OTRO', 'Otro (a)'), ('NINGUNO', 'Ninguno (a)')], default='', max_length=255, verbose_name='De acuerdo con su cultura, pueblo o rasgos físicos, ¿Qué población atienden y ayuda su entidad religiosa? (puede marcar varias)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='principales_inciativas_sociales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PROYECTOS_EDUCATIVOS', 'Proyectos educativos.'), ('PROGRAMAS_SALUD', 'Programas de salud y atención médica.'), ('INICIATIVAS_ALIMENTACION', 'Iniciativas de alimentación para comunidades necesitadas.'), ('PROGRAMAS_VIVIENDA', 'Programas de vivienda para población vulnerable.'), ('APOYO_NINOS_JOVENES', 'Actividades de apoyo a niños y jóvenes en riesgo.'), ('PROYECTOS_COMUNITARIOS', 'Proyectos de desarrollo comunitario.'), ('OTRAS_INICIATIVAS', 'Otros'), ('NO_LLEVADO_A_CABO', 'No hemos llevado a cabo iniciativas o proyectos sociales en Colombia en los últimos años.'), ('NO_SEGURO_NO_APLICABLE', 'No estoy seguro/No aplicable.')], default='', max_length=255, null=True, verbose_name=' ¿Cuáles son las principales iniciativas o proyectos sociales que la Entidad religiosa ha llevado a cabo en Colombia en los últimos años? (puede seleccionar varios)'),
        ),
    ]
