# Generated by Django 4.2.9 on 2024-02-05 17:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0008_rename_otra_idioma_encuesta_otro_idioma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='otros_municipios_actividades',
            new_name='participa_actividades_carida_municipio_otro',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='otros_departamentos_actividades',
            new_name='participa_actividades_caridad_departamento_otro',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='caracter_confesinal_seleccion',
            field=models.CharField(blank=True, choices=[('ASQUENAZIES', 'Asquenazíes'), ('SEFARDIES', 'Sefardíes')], default='', max_length=255, null=True, verbose_name='¿A partir de su respuesta anterior, seleccione la que corresponde? '),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_sociale_representan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante Legal de la Organización del Sector Religioso'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico de la Organización del Sector Religioso'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='impacto_comunidad_valores_cuales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_poblaciones_otro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles son los grupos?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_ciudadana',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DISCRIMINACION_RELIGIOSA', 'Discriminación religiosa'), ('DESCONOCIMIENTO_INSTANCIAS', 'Desconocimiento de las instancias existentes'), ('FALTA_FORMACION_TECNICA', 'Falta de formación técnica'), ('NO_INTERES_EN_PARTICIPAR', 'No tiene interés en participar'), ('SIN_DIFICULTADES', 'No ha tenido dificultades')], default='', max_length=255, null=True, verbose_name='Ha encontrado dificultades para ejercer la participación ciudadana, como ER , en las instancias dispuestas para tal fin por:(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_dificultades',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RUIDO_CON_VECINOS', 'Diferencias con vecinos por ruido.'), ('DANIOS_FISICOS_BIENES_ER', 'Daños físicos a los bienes de la ER'), ('CONTROVERSIAS_PARQUEO', 'Controversias por zonas de parqueo para fieles/asociados.'), ('DOMICILIO_ER', 'Dificultad para establecer el domicilio de su ER'), ('DISCRIMINACION_INTOLERANCIA_RELIGIOSA', 'Discriminación o intolerancia religiosa.'), ('SIN_DIFICULTADES', 'No se han encontrado dificultades')], default='', max_length=255, null=True, verbose_name='Ha encontrado dificultades para ejercer la participación ciudadana, como Entidades Religiosas, lo cual fue consultado por los líderes en las instancias dispuestas para tal fin por: (puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_lideres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LIDERAZGO', 'Formación en liderazgo'), ('GESTION_DE_PAZ', 'Formación en gestión de paz'), ('NORMATIVIDAD_RELIGIOSA', 'Formación en normatividad religiosa'), ('FORMULACION_DE_PROYECTOS_SOCIALES', 'Formulación y presentación de proyectos sociales'), ('TEMATICA_TRIBUTARIA', 'Formación en temática tributaria'), ('GERENCIA_Y_GESTION', 'Gerencia y Gestión'), ('FORTALECIMIENTO_ORGANIZACIONAL_ADMINISTRATIVO', 'Fortalecimiento organizacional y administrativo'), ('OTRA', 'Otra (s)'), ('NINGUNO', 'Ninguno')], default='', max_length=255, null=True, verbose_name=' ¿Líderes de la Entidades Religiosas han recibido capacitación en liderazgo e incidencia pública por parte de los gobiernos territoriales, gobierno nacional, ONG o empresa privada?(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_otra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_tecnica',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EDUCACION', 'Educación'), ('DISCAPACIDAD', 'Discapacidad'), ('ACCION_COMUNAL', 'Acción comunal'), ('VICTIMAS', 'Víctimas'), ('JOVENES', 'Jóvenes'), ('MUJERES', 'Mujeres'), ('INFANCIA_ADOLESCENCIA', 'Infancia y adolescencia'), ('POBLACIONES_VULNERABLES', 'Poblaciones vulnerables'), ('PROPIEDAD_HORIZONTAL', 'Propiedad horizontal'), ('GRUPOS_ETNICOS', 'Grupos étnicos'), ('PLANEACION_PARTICIPATIVA', 'Planeación participativa'), ('PAZ', 'Paz'), ('PARTICIPACION_CIUDADANA', 'Participación ciudadana'), ('PARTICIPACION_POLITICA', 'Participación política')], default='', max_length=255, null=True, verbose_name='hace parte de alguna mesa técnica o temática, Comité, Consejo o Red donde se discutan planes, programas y/o proyectos de interés público o general, tales como:(puede seleccionar varios)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_carida_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿En cuál municipio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_caridad_departamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿En cuál departamento?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_caridad_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descríbalas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_caridad_localidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿En cuál localidad?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='participa_actividades_caridad_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_alianzas_ongs_cuales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico (fundaciones o colegios religiosos)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (fundaciones o colegios religiosos)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_nit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NIT (fundaciones o colegios religiosos)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la organización (fundaciones o colegios religiosos)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono (fundaciones o colegios religiosos'),
        ),
    ]
