# Generated by Django 4.2.9 on 2024-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENCUESTAS', '0010_alter_encuesta__puede_seleccionar_varios__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='celular_extra',
            field=models.CharField(blank=True, null=True, verbose_name='Si tiene otro número de celular o número fijo de contacto escríbalo aquí'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico de la Organización del Sector Religioso'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='colabora_proyectos_sociales_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='impacto_comunidad_valores_cuales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_poblaciones_otro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles son los grupos?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrece_servicios_sociedad_otra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_actividad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra actividad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_areas_temas_prioridad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra áreas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_como_finacia_proyectos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra fuentes'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_discapacidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro discapacidad seleccionada'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_participacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra participacion'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_poblacion_entidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tipo de población seleccionado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_principales_inciativas_sociales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra iniciativas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_vocacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra vocación'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otra_zona_entidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tipo de zona seleccionada'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otro_caracter_confesional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro caracter confesional'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otro_enfoque_principal_servicios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro enfoque principal'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otro_idioma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro idioma'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otro_servicio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro servicio'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otros_beneficios_implementado_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros beneficio implementado en seguridad social'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otros_grupos_personas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro grupo de personas seleccionado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='otros_resultados_destacados',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros resultados'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_carida_municipio_otro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Qué otros municipios tiene actividades?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_caridad_departamento_otro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Qué otros departamentos tiene actividades?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_caridad_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descríbalas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_caridad_localidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿En cuál localidad?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='participa_actividades_caridad_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_alianzas_ongs_cuales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuáles?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico (fundaciones o colegios religiosos)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_nit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NIT (fundaciones o colegios religiosos)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiene_organizaciones_sector_telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono (fundaciones o colegios religiosos'),
        ),
    ]
